### ISSUE TITLE
Label values are not escaped

### ISSUE THREAD

**Issue by gebolze** [nexogen-international/Nexogen.Libraries.Metrics#18]
Based on the Prometheus documentation: https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details

> metric_name and label_name have the usual Prometheus expression language restrictions. label_value can be any sequence of UTF-8 characters, but the backslash, the double-quote, and the line-feed characters have to be escaped as \\, \", and \n, respectively

Actual Output:
```
tokens_login{username="domain\username"} 1 1510911080610
```
Expected Output:
```
tokens_login{username="domain\\username"} 1 1510911080610
```

**Comment by ahoka** [comment]
Thanks for reporting this issue. You have right, it should be escaped. Would you like to contribute a fix?
